steps:
  build:
    image: alpine
    # this step gets ran on "master" branch.
    # also runs on pull requests targeting these branch.
    when:
      branch: [master]
      event: [push, pull_request, manual]
    commands: |
      apk add --no-cache build-base gcc cmake >/dev/null
      mkdir build
      cd build
      cmake ..
      cmake --build .
      ls Release
