name: radicalite-win

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  radicalite-win-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - run: pwd
      - run: ls
      - name: config
        run:
          xmake f -m release --toolchain=mingw
      - name: build
        run:
          xmake -a -v
          
