name: radicalite-win

on: [workflow_dispatch, push, pull_request]
  

permissions:
  contents: read

jobs:
  radicalite-win-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: config
        run:
          xmake f -m release --toolchain=mingw
      - name: build
        run:
          xmake pack
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          path: build/xpack/pack/radicalite-windows.zip
          
